### PR TITLE
:book: move full stop out side of link

### PR DESCRIPTION
**Pull request by markysoft**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-103 in nhsuk-dev succeeded (http://profiles-pr-103.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — COMMENTED** [review]
There is another instance of this in `back-to-choices.nunjucks`. Should this also be updated?

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-103 in nhsuk-dev succeeded (http://profiles-pr-103.dev.c2s.nhschoices.net)

**Comment by markysoft** [comment]
thanks, have moved that full stop too

**Review by st3v3nhunt — APPROVED** [review]
LGTM 👍

**Pull request merged**
