### PR TITLE
🌅 This is a very early implementation of schema.org markup for organi…

### PR DESCRIPTION
**Pull request by sinclr4**
This is a very early implementation of schema.org markup for organisations.

GP's are classed as Physicians within the schema. Currently only the basic org info has been tagged up, with Reception Opening hours and org details.

Potential issues noted are:

Need to split out address data - I have done this as best I could make out from the structure loaded
Opening times needs some work to include surgery. It also merges open and closed into one which needs to be split out
Services have not been tagged up as there is more work to be done around standardising this
Facilities have not been included
Accepting new patients has been added from the life sciences schema.
JSON-LD is the preferred method for including schema.org info

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-168.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-168.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
I've created issue #170 to capture the opening times work to be done

**Comment by st3v3nhunt** [comment]
[Include schema.org markup/json in our pages](https://trello.com/c/58Y0zH1s/11-include-schemaorg-markup-json-in-our-pages)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-168.dev.beta.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Pull request merged**
