### PR TITLE
:strawberry: change default font to fruitger

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-115 in nhsuk-dev succeeded (http://profiles-pr-115.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
Wowsers, this is a big change! Can you rebase please?

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-115 in nhsuk-dev succeeded (http://profiles-pr-115.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
Closing as PR #128 supersedes it

**Pull request closed without merging**
