### PR TITLE
:passport_control: Run Travis tests with docker-compose

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-15.dev.c2s.nhschoices.net](http://profiles-pr-15.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-15.dev.c2s.nhschoices.net](http://profiles-pr-15.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-15.dev.c2s.nhschoices.net](http://profiles-pr-15.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-15.dev.c2s.nhschoices.net](http://profiles-pr-15.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
Looks good

**Pull request merged**
