### PR TITLE
:phone: added more contact details

### PR DESCRIPTION
**Pull request by markysoft**
Added email and fax number.
Phone, fax, email are hidden if not present.

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-48.dev.c2s.nhschoices.net](http://profiles-pr-48.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — COMMENTED** [review]
LGTM. I'd like to get confirmation the non-display of the fields is correct before merging.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-48.dev.c2s.nhschoices.net](http://profiles-pr-48.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
👍

**Pull request merged**
