### PR TITLE
:ship: Use normal user instead of root

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:warning: deployment of 51 for nhsuk/profiles failed

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-51.dev.c2s.nhschoices.net](http://profiles-pr-51.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-51.dev.c2s.nhschoices.net](http://profiles-pr-51.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-51.dev.c2s.nhschoices.net](http://profiles-pr-51.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — CHANGES_REQUESTED** [review]
@adamgraves-choices A couple of tweaks in PR #70 if you want to have a look and merge them into this branch.
Once those changes are in, i'm happy to merge this.

**Comment by adamgraves-choices** [comment]
@st3v3nhunt Thanks. Merged those changes now.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-51.dev.c2s.nhschoices.net](http://profiles-pr-51.dev.c2s.nhschoices.net)

**Review by neilbmclaughlin — APPROVED** [review]

**Review by st3v3nhunt — APPROVED** [review]

**Pull request merged**
