### PR TITLE
 Implement frontend library

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
:nail_care: implement frontend library

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-197.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-197.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-197.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-197.dev.beta.nhschoices.net)

**Review by beseven — APPROVED** [review]
LOTM! Compared to c2s repo and tested in browserstack on a range of devices and browsers

**Pull request merged**
