### PR TITLE
:put_litter_in_its_place: Delete generated css

### LINKED ISSUE #24: Remove contents of /public/css
The contents are generated during image creation, therefore the `.css` files aren't being used and should be removed to avoid any confusion

### PR DESCRIPTION
**Pull request by st3v3nhunt**
There are no `public/components`, in this repo they are stored under `public/css`.
When this is deployed to a test environment need to check the styling is available. If so, all is good.

Fixes #24

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-46.dev.c2s.nhschoices.net](http://profiles-pr-46.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
Styling still in tact e.g. http://profiles-pr-46.dev.c2s.nhschoices.net/gp-surgeries/43212

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-46.dev.c2s.nhschoices.net](http://profiles-pr-46.dev.c2s.nhschoices.net)

**Review by neilbmclaughlin — APPROVED** [review]

**Comment by neilbmclaughlin** [comment]
@ajthomascouk - feel free to merge.

**Pull request merged**
