### PR TITLE
Remove rancher templates dependency

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-135.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-135.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-135.dev.beta.nhschoices.net)

**Review by markysoft — APPROVED** [review]
Verified deployed site, tests and local containers. Checked code. Looks good to me.

**Pull request merged**
