### PR TITLE
Feature/remove fs me

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by ajthomascouk** [comment]
https://profiles-pr-207.dev.beta.nhschoices.net/gp-surgeries/43212

**Comment by st3v3nhunt** [comment]
Looks like there are 4 references to the font:
screen shot 2017-08-08 at 09 25 18

**Review by st3v3nhunt — CHANGES_REQUESTED** [review]
There are another 3 references to the font - I guess they'll need removing too?

**Comment by ajthomascouk** [comment]
eh!? - Where have they come from?

**Comment by ajthomascouk** [comment]
Not sure how they were missed. The `c2s-ie.scss` file wasn't committed initially, despite there being changes.

**Comment by st3v3nhunt** [comment]
There are a lot of changes in `yarn.lock`. As there are no changes in `package.json` I'm not sure why this has happened. It would be preferential if those changes were removed from this commit.

**Comment by ajthomascouk** [comment]
> There are a lot of changes in yarn.lock. As there are no changes in package.json I'm not sure why this has happened. It would be preferential if those changes were removed from this commit.

Tried and mashed up my branch. I'll delete this and start again. The changes are minimal anyway.

**Pull request closed without merging**
