### PR TITLE
Use Vault in CI scripts

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-166.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-166.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-166.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-166.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-166.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-166.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
LGTM, site deployed with env vars in place.

**Pull request merged**
