### PR TITLE
Feature/remove profiles

### LINKED ISSUE #12: Remove 'profiles' segment from routing
No need for `/profiles` in the routing

### PR DESCRIPTION
**Pull request by st3v3nhunt**
Mostly routing changes and some simplification of view names. Change of behaviour when an unknown code is entered. Rather than returning a `202` a `404` will now be returned.

Fixes #12

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-14.dev.c2s.nhschoices.net](http://profiles-pr-14.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
Looks good.

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-14.dev.c2s.nhschoices.net](http://profiles-pr-14.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-14.dev.c2s.nhschoices.net](http://profiles-pr-14.dev.c2s.nhschoices.net)

**Pull request merged**
