### PR TITLE
:honeybee: remove border from last row and reduce padding

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-148.dev.beta.nhschoices.net)

**Comment by ajthomascouk** [comment]
@alex-colbeck please can you take a look at the two specific profiles, mentioned by @beseven on [trello](https://trello.com/c/AoMAlIih/303-feature-display-exceptional-opening-dates-and-times#comment-5927da6506afbe4505093203):

* http://profiles-pr-148.dev.beta.nhschoices.net/gp-surgeries/36036
* http://profiles-pr-148.dev.beta.nhschoices.net/gp-surgeries/42056

We'll have to manipulate the data to see the fix for the [issue raised](https://github.com/nhsuk/profiles/issues/146). Let me know when you want to do this.

**Review by alex-colbeck — APPROVED** [review]
🚒  Looks good

**Review by st3v3nhunt — APPROVED** [review]
The changes look good. Given the tests were broken with no changes to the underlying data I assume that they will start to break again from 00:01 Tuesday 30th?

**Comment by ajthomascouk** [comment]
@st3v3nhunt wrote:
> Given the tests were broken with no changes to the underlying data I assume that they will start to break again from 00:01 Tuesday 30th?

Raised an [issue](https://github.com/nhsuk/profiles/issues/150)

**Pull request merged**
