### PR TITLE
:cactus: table styles for mobiles

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-92.dev.c2s.nhschoices.net](http://profiles-pr-92.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-92.dev.c2s.nhschoices.net/gp-surgeries/41313](http://profiles-pr-92.dev.c2s.nhschoices.net/gp-surgeries/41313)

**Comment by st3v3nhunt** [comment]
LGTM. I'll merge when reviewed by @mcgrathjoe

**Review by st3v3nhunt — APPROVED** [review]
All good

**Pull request merged**
