### PR TITLE
Feature/docker compose

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-7.dev.c2s.nhschoices.net](http://profiles-pr-7.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
@markysoft Try this. The environment will be set to `development` to ensure all dev deps are installed.

**Comment by st3v3nhunt** [comment]
:rocket: deployed to [http://profiles-pr-7.dev.c2s.nhschoices.net](http://profiles-pr-7.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
Verified both files run the app or tests, and changes are reflected in the running instance

**Pull request merged**
