### PR TITLE
:new: new patients, how to register

### PR DESCRIPTION
**Pull request by markysoft**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-99 in nhsuk-dev succeeded (http://profiles-pr-99.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-99 in nhsuk-dev succeeded (http://profiles-pr-99.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-99 in nhsuk-dev succeeded (http://profiles-pr-99.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-99 in nhsuk-dev succeeded (http://profiles-pr-99.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-99 in nhsuk-dev succeeded (http://profiles-pr-99.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
LGTM 👍

**Pull request merged**
