### PR TITLE
:bug: fix url from profile page to book page

### PR DESCRIPTION
**Pull request by beseven**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-45.dev.c2s.nhschoices.net](http://profiles-pr-45.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
Rebasing now

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-45.dev.c2s.nhschoices.net](http://profiles-pr-45.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Pull request merged**
