### PR TITLE
:ghost: Who you gonna call?

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-139 in nhsuk-dev succeeded (http://profiles-pr-139.dev.beta.nhschoices.net)

**Review by st3v3nhunt — COMMENTED** [review]
Does it need adding to the HJ file also? https://github.com/nhsuk/profiles/pull/139/files#diff-31c187f91006c58fed5de1f2da5abd37R57

**Comment by ajthomascouk** [comment]
@st3v3nhunt wrote:
> Does it need adding to the HJ file also?

Well spotted. I added it to GA by mistake. No harm tho I guess.

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-139 in nhsuk-dev succeeded (http://profiles-pr-139.dev.beta.nhschoices.net)

**Comment by ajthomascouk** [comment]
@st3v3nhunt back to you mate.

**Review by st3v3nhunt — APPROVED** [review]
🥇

**Pull request merged**
