### PR TITLE
:black_nib: Leave a review link added

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Review by st3v3nhunt — CHANGES_REQUESTED** [review]
A couple of questions:

* Should the link for `ratings and reviews` have a webtrends tag on?
* Can a test be added to ensure the link for the `ratings and reviews` link is correct please?

I'm not sure but I think the query string version for the webtrends js will need incrementing to 2 as the file has been changed.

There a quite a number of commits that could be squashed too. I don't think having commits for 'fixing test' is going to be all that useful in the future.

**Comment by ajthomascouk** [comment]
@st3v3nhunt wrote:
> Should the link for ratings and reviews have a webtrends tag on?

Very good point!

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-172.dev.beta.nhschoices.net)

**Comment by ajthomascouk** [comment]
Recreated on PR174

**Pull request closed without merging**
