### PR TITLE
:interrobang: Ensure PR environment is always rebuilt

### LINKED ISSUE #42: Update ci-deployment scripts

### PR DESCRIPTION
**Pull request by st3v3nhunt**
Fixes #42

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-43.dev.c2s.nhschoices.net](http://profiles-pr-43.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-43.dev.c2s.nhschoices.net](http://profiles-pr-43.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-43.dev.c2s.nhschoices.net](http://profiles-pr-43.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-43.dev.c2s.nhschoices.net](http://profiles-pr-43.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-43.dev.c2s.nhschoices.net](http://profiles-pr-43.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
When this is merged please delete https://github.com/nhsuk/ci-deployment/tree/feature/profiles-with-db

**Review by markysoft — APPROVED** [review]
LGTM

**Pull request merged**
