### PR TITLE
:syringe: GP counts and names

### PR DESCRIPTION
**Pull request by markysoft**
Display GP counts and names

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-47.dev.c2s.nhschoices.net](http://profiles-pr-47.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-47.dev.c2s.nhschoices.net](http://profiles-pr-47.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — CHANGES_REQUESTED** [review]
Looks good. One thing I probably would have done differently is to have pre-calculated the value of `doctorsAvailable(gp.gpCounts)`. Instead of calling the function and passing the value to it within the view, something like a function in the form `areGPsAvailable()`.

Is there a specific reason this uses `doctors` rather than `GPs`? If not, it would be good to use the latter for consistency.

**Review by st3v3nhunt — DISMISSED** [review]

**Comment by markysoft** [comment]
Renamed doctor to GPs in methods. Will move the methods exposed in the renderer into middleware to create a view model in future iterations.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-47.dev.c2s.nhschoices.net](http://profiles-pr-47.dev.c2s.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
👍

**Pull request merged**
