### PR TITLE
:back: activate back button for book-appointment

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-41.dev.c2s.nhschoices.net/gp-surgeries/41232/book-appointment](http://profiles-pr-41.dev.c2s.nhschoices.net/gp-surgeries/41232/book-appointment)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-41.dev.c2s.nhschoices.net/gp-surgeries/41232/book-appointment](http://profiles-pr-41.dev.c2s.nhschoices.net/gp-surgeries/41232/book-appointment)

**Comment by ajthomascouk** [comment]
I tried to be clever with my previous commit comments whilst rebasing and I seem to have removed them all :see_no_evil:

**Comment by st3v3nhunt** [comment]
@ajthomascouk What do you think to this way of doing the back link rather than hardcoding it with JS in the view? I should have branched rather than overwriting yours! Sorry.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-41.dev.c2s.nhschoices.net](http://profiles-pr-41.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-41.dev.c2s.nhschoices.net](http://profiles-pr-41.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-41.dev.c2s.nhschoices.net](http://profiles-pr-41.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Comment by ajthomascouk** [comment]
@st3v3nhunt wrote:
> What do you think to this way of doing the back link rather than hardcoding it with JS in the view?

To be fair I tried that way first, but couldn't get it to pass Travis.

**Pull request merged**
