### PR TITLE
:mag: Use ADRs for recording architecture decisions

### PR DESCRIPTION
**Pull request by st3v3nhunt**
See https://github.com/npryce/adr-tools#adr-tools for tooling

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-157.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-157.dev.beta.nhschoices.net)

**Review by beseven — CHANGES_REQUESTED** [review]
Looking good, can you add something about this in the README please

**Comment by st3v3nhunt** [comment]
@beseven updated

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-157.dev.beta.nhschoices.net)

**Review by beseven — APPROVED** [review]
LGTM!

**Pull request merged**
