### PR TITLE
Feature/fake data front end

### PR DESCRIPTION
**Pull request by st3v3nhunt**
This is to be merged into `master` once the #31 has been merged. Leaving as WIP until that time

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-38.dev.c2s.nhschoices.net](http://profiles-pr-38.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-38.dev.c2s.nhschoices.net](http://profiles-pr-38.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-38.dev.c2s.nhschoices.net](http://profiles-pr-38.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-38.dev.c2s.nhschoices.net](http://profiles-pr-38.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-38.dev.c2s.nhschoices.net](http://profiles-pr-38.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-38.dev.c2s.nhschoices.net](http://profiles-pr-38.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Pull request merged**
