### PR TITLE
:bouquet: Remove online booking link logic

### PR DESCRIPTION
**Pull request by st3v3nhunt**
In preference to using pre-calculated values in the db.

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
I'm going to leave this as WIP until https://github.com/nhsuk/profiles-db/pull/23 is merged and tagged as a release at which point i'll update the docker-compose files to use those tagged docker images.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-69.dev.c2s.nhschoices.net](http://profiles-pr-69.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-69.dev.c2s.nhschoices.net](http://profiles-pr-69.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Pull request merged**
