### PR TITLE
:dog: Run snyk on CI

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-131 in nhsuk-dev succeeded (http://profiles-pr-131.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-131 in nhsuk-dev succeeded (http://profiles-pr-131.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-pr-131 in nhsuk-dev succeeded (http://profiles-pr-131.dev.beta.nhschoices.net)

**Review by beseven — APPROVED** [review]
LGTM!

**Pull request merged**
