### PR TITLE
:speaker: Extra info when no link for booking online

### PR DESCRIPTION
**Pull request by st3v3nhunt**
Presentation tweaks

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-60.dev.c2s.nhschoices.net](http://profiles-pr-60.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-60.dev.c2s.nhschoices.net](http://profiles-pr-60.dev.c2s.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-pr-60.dev.c2s.nhschoices.net](http://profiles-pr-60.dev.c2s.nhschoices.net)

**Pull request merged**
