### PR TITLE
:capital_abcd: Make GP names title case

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles succeeded (http://profiles-pr-149.dev.beta.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
I realise it's WIP but the PR caught my attention so thought I'd chip in.

Dr McLaughlin isn't happy (http://profiles-pr-149.dev.beta.nhschoices.net/gp-surgeries/35425) neither is Dr O'Neill (http://profiles-pr-149.dev.beta.nhschoices.net/gp-surgeries/36194). Especially given the casing for them is correct in the source data.

Could we use this package https://www.npmjs.com/package/namecase?

Maybe even something we should be doing server side or in the ETL

cc @ajthomascouk @markysoft

**Comment by ajthomascouk** [comment]
@neilbmclaughlin I spoke a bit with @mcgrathjoe about this. I 100% agree that this shouldn't be done at template level. I thought that the `| title` filter was better than nothing?

Im guessing that using [namecase](https://www.npmjs.com/package/namecase) would still be "frontend"? I think the best place for it is at ETL level.

**Comment by neilbmclaughlin** [comment]
Agree that this should probably be part of the ETL. Happy for it to be closed.

**Comment by st3v3nhunt** [comment]
Closing based on comments above (and the fact it is currently 133 commits behind `master`)

**Pull request closed without merging**
